data(k).Rprob = choice; %information / points. input to learning model
data(k).lapse1 = lapse1;
data(k).deckchoice = deckchoice;
data(k).RT1 = RT1;
data(k).choice_onset = choice_onset;
data(k).press1_onset = press1_onset;
data(k).info_onset = info_onset;
data(k).fix1_list = fix1_list(k);
data(k).fix2_list = fix2_list(k);
data(k).block = block;
data(k).feedback = correct;
data(k).seq = seq;
